//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQuanLyKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichLamViec
    {
        public int LichLamViecID { get; set; }
        public Nullable<int> NhanVienID { get; set; }
        public string Ca { get; set; }
        public string Ngay { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
