//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQuanLyKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class MatKhau
    {
        public string username { get; set; }
        public string password { get; set; }
        [DataType("confirminPassword")]
        [Compare("password",ErrorMessage ="Mat khau khong dung")]
        public string confirminPassword { get; set; }
    }
}
