//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemQuanLyKhachSan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatTu
    {
        public int VatTuID { get; set; }
        public string TenVT { get; set; }
    }
}
